fix(greenhouses): recupération des greenhouse par building
Progeser/progeser-api pull request #78
Opened 2024-11-05 16:25 UTC by Lelievre-david

2024-11-05 16:27 UTC, Romain-Lecleire approved these changes

2024-11-05 16:41 UTC, Tao-Galasse requested changes
Cette refacto inclut des breaking changes, il faut donc penser à mettre à jour tes tests (et donc ta doc API) pour les prendre en conséquences : tu n'appelles plus `/api/v1/greenhouses` par exemple, mais `/api/v1/buildings/:building_id/benches`.

Quand tu auras mis à jour tout ça et que les tests seront au vert, tu pourras en profiter pour re-générer la doc API :) 
Pour ça, tu peux utiliser la commande `bundle exec rake docs:generate` (cf la documentation de la gem qui génère la doc [ici](https://github.com/zipmark/rspec_api_documentation))

2024-11-06 11:10 UTC, Tao-Galasse approved these changes
top 👌

2024-11-06 11:10 UTC, Tao-Galasse commented on spec/acceptance/api/v1/greenhouses_controller_spec.rb
> +      do_request(building_id:)
```suggestion
      do_request
```

2024-11-06 11:54 UTC, Romain-Lecleire approved these changes

2024-11-06 11:54 UTC, Romain-Lecleire approved these changes

2024-11-06 13:37 UTC, merged

2024-11-06 15:40 UTC, Tao-Galasse commented on spec/acceptance/api/v1/greenhouses_controller_spec.rb
> +      do_request(building_id:)
@Romain-Lecleire il faudra bien penser à l'enlever malgré tout, le `do_request` ne prend pas d'arguments :)