f
Progeser/progeser-api pull request #81
Opened 2024-11-27 10:08 UTC by Lelievre-david

2024-11-27 16:15 UTC, Tao-Galasse requested changes
C'est quand même un peu dommage côté UX, parce que dans ce nouveau flow, un utilisateur demande à créer un compte...

...et n'est jamais prévenu quand sa demande a été acceptée :/

Donc, à part en venant au hasard de temps en temps sur le site pour essayer de se connecter, il n'a aucun moyen de savoir si son accès est disponible ou pas.

C'est une régression assez pénalisante, je trouve 😕 

Et si de toute façon on n'envoie plus de mail, utiliser le principe même des account_requests ne sert plus à rien (et nous embête même plus qu'autre chose à cause de la conservation du password).
Quitte à refactoriser ça, on aurait pu s'affranchir de cette table, n'utiliser qu'un modèle User, et pourquoi pas lui ajouter un attribut booléen du genre `active`, à false par défaut, et qui ne passe à true que lorsqu'un grower accepte la demande, ou quelque chose comme ça ? 🤔 Et bien sûr, empêcher la connexion pour tout user qui n'est pas "active".

Avec cette implem, on a toujours les problèmes évoqués plus haut, mais on a au moins un code plus clair, et plus de souci de password.

Qu'en pensez-vous ? :)

2024-11-27 16:15 UTC, Tao-Galasse commented on app/controllers/api/v1/users_controller.rb
> -    account_request = AccountRequest.find_by!(creation_token: params[:creation_token])
si on supprime cette méthode, ça veut dire que le champ `creation_token` de l'AccountRequest n'est plus nécessaire ; 

et de même, avec la suppression du reset_password, le `confirmation_token` du User n'est plus nécessaire non plus.

2024-11-27 16:15 UTC, Tao-Galasse commented on app/interactors/account_requests/accept.rb
> +      encrypted_password: account_request.password_digest
et on est sûr que ça marche ça ? J'aurais tendance à penser que non 🤔 

Ça n'est pas testé dans nos specs ici, et en l'occurrence, le password du modèle User étant chiffré par `Clearance` alors que celui de l'AccountRequest l'est par `bcrypt`. Ça se voit d'ailleurs sur les noms des clés : l'un dispose d'un `password_digest`, l'autre d'un `encrypted_password`. Je ne pense pas que l'un puisse être transféré à l'autre de la sorte ; il faudrait tester pour s'en assurer, mais je n'y crois pas trop ; pour moi, en l'état, cette feature ne fonctionne pas 😬

2024-12-09 11:36 UTC, MisterOryon commented on test/models/request_test.rb
> -# == Schema Information
Pourquoi il y a plus le "Schema Information" ?

2024-12-09 13:04 UTC, MisterOryon approved these changes
lgtm

2024-12-09 13:21 UTC, merged

2024-12-12 10:19 UTC, Tao-Galasse reviewed
Désolé, j'ai été pas mal pris ces derniers temps, je rattrape mon retard sur vos PR !

Mais c'est top, belle simplification de toute la logique et bonne implémentation, bravo 👌 👏

2024-12-12 10:19 UTC, Tao-Galasse commented on config/routes.rb
> +      resources :users, only: :index
comment vous comptez gérer la création d'un nouvel utilisateur serriste, finalement ? :)

2024-12-12 10:19 UTC, Tao-Galasse commented on app/policies/request_policy.rb
> +    end
simple remarque de style, mais on écrirait plutôt ça comme en ruby : 
```suggestion
    return true if record.pending?

    record.errors.add(:status, 'can\'t delete a non-pending request')
    false
```
(en gros, on évite les if/else si un simple if qui met fin à la méthode suffit ! Ça allège la lecture et la "charge mentale" de la logique :) )